version: '3.8'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
    - "8011:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=journey_hub_db

  db:
    image: postgres:12.13
    hostname: journey_hub_db
    ports:
     - "5432:5432"
    volumes:
     - /var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6381:6379"

  job-worker:
    build: .
    command: celery -A celery_worker worker --loglevel=INFO -E -B
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis
      - POSTGRES_HOST=journey_hub_db
    volumes:
      - .:/app
