# Generated by Django 4.1.7 on 2023-05-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='feedback',
            field=models.TextField(null=True),
        ),
    ]
