# Generated by Django 4.1.7 on 2023-04-01 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                (
                    "destination_type",
                    models.CharField(
                        choices=[
                            ("city", "City"),
                            ("country", "Country"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("rating", models.FloatField()),
                ("ratings_count", models.IntegerField()),
                ("views_count", models.IntegerField()),
                ("image_urls", models.JSONField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to="planning.location",
                    ),
                ),
                (
                    "parent_destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="planning.destination",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
