# Generated by Django 4.1.7 on 2023-04-22 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0004_alter_suggestionresults_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estimated_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "amount_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "budget_category",
                    models.CharField(
                        choices=[
                            ("Accommodation", "Accommodation"),
                            ("Transportation", "Transportation"),
                            ("Food and Drink", "Food and Drink"),
                            (
                                "Activities and Entertainment",
                                "Activities and Entertainment",
                            ),
                            ("Shopping", "Shopping"),
                            ("Miscellaneous", "Miscellaneous"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_entries",
                        to="planning.trip",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(max_length=3, null=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="planning.trip",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
