# Generated by Django 4.1.7 on 2023-04-22 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0005_budgetentry_budget"),
    ]

    operations = [
        migrations.RenameField(
            model_name="budgetentry",
            old_name="budget_category",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="budgetentry",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="planning.budget",
            ),
        ),
    ]
