# Generated by Django 4.1.7 on 2023-05-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0006_rename_budget_category_budgetentry_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
