# Generated by Django 4.1.7 on 2023-05-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0007_attraction_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="budget_category",
            field=models.CharField(
                choices=[
                    ("Accommodation", "Accommodation"),
                    ("Transportation", "Transportation"),
                    ("Food and Drink", "Food and Drink"),
                    ("Activities", "Activities"),
                    ("Shopping", "Shopping"),
                    ("Miscellaneous", "Miscellaneous"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="budgetentry",
            name="category",
            field=models.CharField(
                choices=[
                    ("Accommodation", "Accommodation"),
                    ("Transportation", "Transportation"),
                    ("Food and Drink", "Food and Drink"),
                    ("Activities", "Activities"),
                    ("Shopping", "Shopping"),
                    ("Miscellaneous", "Miscellaneous"),
                ],
                max_length=255,
            ),
        ),
    ]
