# Generated by Django 4.1.7 on 2023-05-07 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0008_alter_attraction_budget_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripattraction",
            name="attraction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_attractions",
                to="planning.attraction",
            ),
        ),
    ]
