# Generated by Django 4.1.7 on 2023-05-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_attraction_rates_destination_rates_customimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='ratings_count',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='ratings_count',
        ),
    ]
