# Generated by Django 4.1.7 on 2023-05-20 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_remove_customexpense_destination_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='customexpense',
            name='attraction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_expenses', to='planning.attraction'),
        ),
    ]
