# Generated by Django 4.1.7 on 2023-05-09 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0010_customexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExcursionBooking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('session_url', models.TextField()),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursion_bookings', to='excursions.excursion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursion_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExcursionAttraction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.attraction')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursion_attractions', to='excursions.excursion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
