# Generated by Django 4.1.7 on 2023-05-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='start_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='adults_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='children_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='phone_number',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
