# Generated by Django 4.1.7 on 2023-05-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0002_excursion_start_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionbooking',
            name='session_url',
            field=models.TextField(null=True),
        ),
    ]
