# Generated by Django 4.1.7 on 2023-05-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0003_alter_excursionbooking_session_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursionbooking',
            name='status',
        ),
        migrations.AlterField(
            model_name='excursionbooking',
            name='adults_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='excursionbooking',
            name='payment_status',
            field=models.CharField(default='new', max_length=255),
        ),
    ]
