# Generated by Django 4.1.7 on 2023-05-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0004_remove_excursionbooking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionbooking',
            name='session_id',
            field=models.TextField(null=True),
        ),
    ]
